import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { ReactFragment, ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

interface BoardPost {
	id: number;
  imageUrl: string;
  description: string;
  username: string;
  type: string;
  timestamp: Date
}
const essencesData1: BoardPost = {
	id: 1,
  imageUrl: "http://www.vhpg.com/img-build/poe-currency-tab.png",
  description:
    "red essennce x 3, blue essences x 3, green essences x 3, yellow essences",
  username: "JamesGordon",
  type: "essence",
  timestamp: new Date()
  
};
const postListData = [];
for(let i = 0; i < 10; i++) {
	postListData.push(essencesData1);
}

export default function Home() {
  const postList = postListData.map((x) => {
    return (
      <div key={x.id} className="flex flex-col gap-4 shadow-lg p-4 bg-white rounded-lg">
        <p className="text-right text-sm text-gray-400">{x.timestamp.toLocaleDateString("en-US")}</p>
		
		<img src={x.imageUrl} alt='image of stash tab' className="border rounded-lg" />
		<p>{x.description}</p>

		<p className="px-3 text-right text-sm">username: {x.username}</p>
		<button className='rounded bg-blue-400 py-3 text-white'>whisper</button>
      </div>
    );
  });
  return (
    <>
      <Head>
        <title>Poe Bulk Trade Board</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-slate-100 p-4">
		<p className="text-3xl text-center pt-4 pb-10 font-serif underline">essences</p>
        <div className='grid grid-cols-4 gap-6'>
          {postList}
        </div>
      </main>
    </>
  );
}
